CREATE TABLE lead (
id SERIAL,
full_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
phone VARCHAR(15),
PRIMARY KEY (id)
);

CREATE TABLE activity (
id SERIAL,
activity_type VARCHAR(50) NOT NULL,
activity_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);